name: Build, Test, and Push Docker Image 🚀

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t yuriy235/carrentalblazor .

      - name: Log in to Docker Hub
        run: echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push image to Docker Hub
        run: docker push yuriy235/carrentalblazor

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker-compose down || true
          docker-compose up -d
      
      - name: Wait for the application to be ready
        run: |
          echo "Waiting for the application to start..."
          for i in {1..30}; do
            if curl -s http://localhost:7063/api/users > /dev/null; then
              echo "Application is ready!"
              exit 0
            fi
            sleep 2
          done
          echo "Application failed to start."
          exit 1

      - name: Run K6 performance tests
        run: |
          docker run --network="host" -v ${{ github.workspace }}/load-tests:/scripts loadimpact/k6 run /scripts/constant_vus_test.js

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down