name: Build, Test, and Push Docker Image 🚀

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t yuriy235/carrentalblazor .

      - name: Log in to Docker Hub
        run: echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push image to Docker Hub
        run: docker push yuriy235/carrentalblazor

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Set up Docker Compose
        working-directory: ${{ github.workspace }}
        run: |
          docker-compose down || true
          docker-compose up -d
          # Wait for the app to be ready
          sleep 20

      - name: Run K6 Test - Constant VUs
        working-directory: ${{ github.workspace }}
        run: |
          docker run --network="carrentingsystemblazor_default" \
            -v ${{ github.workspace }}/load-tests:/scripts \
            grafana/k6 run /scripts/constant_vus_test.js

      - name: Run K6 Test - Ramping VUs
        working-directory: ${{ github.workspace }}
        run: |
          docker run --network="carrentingsystemblazor_default" \
            -v ${{ github.workspace }}/load-tests:/scripts \
            grafana/k6 run /scripts/ramping_vus_test.js

      - name: Run K6 Test - Constant Arrival Rate
        working-directory: ${{ github.workspace }}
        run: |
          docker run --network="carrentingsystemblazor_default" \
            -v ${{ github.workspace }}/load-tests:/scripts \
            grafana/k6 run /scripts/constant_arrival_rate_test.js

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: k6-test-reports
          path: |
            ${{ github.workspace }}/load-tests/report_constant_vus.html
            ${{ github.workspace }}/load-tests/report_ramping_vus.html
            ${{ github.workspace }}/load-tests/report_arrival_vus.html

      - name: Output Application Logs
        if: failure()
        run: |
          echo "Application logs:"
          docker logs $(docker ps -q --filter "name=carrentingsystemblazor-app-1")

      - name: Tear down Docker Compose
        if: always()
        working-directory: ${{ github.workspace }}
        run: docker-compose down