name: Build, Test, and Push Docker Image 🚀

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t yuriy235/carrentalblazor .

      - name: Log in to Docker Hub
        run: echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push image to Docker Hub
        run: docker push yuriy235/carrentalblazor

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml down || true
          docker-compose -f docker-compose.yml up -d
      
      - name: Run K6 performance tests
        run: |
          docker-compose up -d # Ensure all services are running
          docker run --network="carrentingsystemblazor_default" -v ${{ github.workspace }}/load-tests:/scripts grafana/k6 run /scripts/constant_vus_test.js

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose -f docker-compose.yml down

      - name: Output Application Logs
        if: failure()
        run: |
          echo "Application logs:"
          docker logs $(docker ps -q --filter "name=carrentingsystemblazor-app-1")
